// ─────────────────────────────────────────────────────────────────────────────
// TacticalCanvas — Shared Type Contracts
// ─────────────────────────────────────────────────────────────────────────────
// Every widget in this system shares these types. No component should define
// its own `any`-typed feature, asset, or alert shape.
// ─────────────────────────────────────────────────────────────────────────────

/** The four classifiable feature layers in the GEOINT module. */
export type FeatureType = 'infrastructure' | 'pathway' | 'organic' | 'zone';

/** A single geographic feature generated by the cluster engine. */
export interface GeoFeature {
  type: FeatureType;
  lng: number;
  lat: number;
}

/** Filter toggle state for each feature layer. */
export type FilterState = Record<FeatureType, boolean>;

/** The four top-level operational modules. */
export type ActiveModule = 'GEOINT' | 'RADAR' | 'TARGETING' | 'COMMAND';

export type GeoJsonPrimitive = string | number | boolean | null;
export type GeoJsonPropertyValue = GeoJsonPrimitive | GeoJsonPrimitive[] | Record<string, GeoJsonPrimitive>;

export interface LayerFeatureProperties {
  category?: FeatureType;
  name?: string;
  description?: string;
  assetId?: string;
  targetId?: string;
  timestamp?: string;
  [key: string]: GeoJsonPropertyValue | undefined;
}

export type GeoJsonPosition = [number, number] | [number, number, number];
export type BBox = [number, number, number, number];

export interface GeoJsonPointGeometry {
  type: 'Point';
  coordinates: GeoJsonPosition;
}

export interface GeoJsonMultiPointGeometry {
  type: 'MultiPoint';
  coordinates: GeoJsonPosition[];
}

export interface GeoJsonLineStringGeometry {
  type: 'LineString';
  coordinates: GeoJsonPosition[];
}

export interface GeoJsonMultiLineStringGeometry {
  type: 'MultiLineString';
  coordinates: GeoJsonPosition[][];
}

export interface GeoJsonPolygonGeometry {
  type: 'Polygon';
  coordinates: GeoJsonPosition[][];
}

export interface GeoJsonMultiPolygonGeometry {
  type: 'MultiPolygon';
  coordinates: GeoJsonPosition[][][];
}

export type GeoJsonGeometry =
  | GeoJsonPointGeometry
  | GeoJsonMultiPointGeometry
  | GeoJsonLineStringGeometry
  | GeoJsonMultiLineStringGeometry
  | GeoJsonPolygonGeometry
  | GeoJsonMultiPolygonGeometry;

export interface GeoJsonFeature<P extends LayerFeatureProperties = LayerFeatureProperties> {
  type: 'Feature';
  id: string;
  geometry: GeoJsonGeometry;
  properties: P;
  bbox?: BBox;
}

export interface GeoJsonFeatureCollection<P extends LayerFeatureProperties = LayerFeatureProperties> {
  type: 'FeatureCollection';
  features: GeoJsonFeature<P>[];
  bbox?: BBox;
}

export type LayerSourceType = 'sample' | 'geojson-file' | 'geojson-url';
export type LayerDisplayMode = 'circle' | 'line' | 'fill';

export interface LayerStyle {
  color: string;
  outlineColor?: string;
  radius?: number;
  width?: number;
  fillOpacity?: number;
  lineDasharray?: number[];
}

export interface LayerSourceConfig {
  label: string;
  fileName?: string;
  url?: string;
  importedAt?: string;
}

export interface LayerDefinition<P extends LayerFeatureProperties = LayerFeatureProperties> {
  id: string;
  name: string;
  sourceType: LayerSourceType;
  sourceConfig: LayerSourceConfig;
  data: GeoJsonFeatureCollection<P>;
  displayModes: LayerDisplayMode[];
  style: LayerStyle;
  visible: boolean;
  opacity: number;
  zIndex: number;
  locked: boolean;
  minZoom: number;
  maxZoom: number;
  status: 'ready' | 'loading' | 'error';
  error?: string;
}

export interface MapFeatureRef {
  layerId: string;
  featureId: string;
}

export interface MapViewportState {
  center: [number, number];
  zoom: number;
  bearing: number;
  pitch: number;
}

export type MapHealthState = 'ready' | 'degraded' | 'failed';

export interface MapFocusRequest {
  kind: 'layer' | 'feature';
  layerId: string;
  featureId?: string;
  token: number;
}

export interface FeatureSummary {
  total: number;
  infrastructure: number;
  pathway: number;
  organic: number;
  zone: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// Asset Model
// ─────────────────────────────────────────────────────────────────────────────

export type AssetStatus = 'ACTIVE' | 'RTB' | 'LOITER' | 'TRACKED';

export interface Asset {
  id: string;
  type: string;
  status: AssetStatus;
  fuel: number;
  /** Radar position — percentage-based, 0-100. */
  radarX: number;
  radarY: number;
  /** Heading in degrees for the radar marker. */
  heading: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// Alert Model
// ─────────────────────────────────────────────────────────────────────────────

export type AlertLevel = 'CRITICAL' | 'WARNING' | 'INFO';

export interface Alert {
  id: string;
  level: AlertLevel;
  msg: string;
  time: string;
  /** Optional link to the asset that caused the alert. */
  assetId?: string;
  /** Optional link to the target implicated in the alert. */
  targetId?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Targeting Model
// ─────────────────────────────────────────────────────────────────────────────

export interface TargetMarker {
  id: string;
  type: string;
  x: number;
  y: number;
  size: 'sm' | 'md' | 'lg';
  dist: string;
}

export type MissionTaskStatus = 'ACTIVE';

export interface MissionTask {
  assetId: string;
  targetId: string;
  status: MissionTaskStatus;
  createdAt: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Mission State — the shared selection context that flows across all modules
// ─────────────────────────────────────────────────────────────────────────────

export interface MissionState {
  /** Currently selected asset (from AssetList or Radar). null = nothing selected. */
  selectedAssetId: string | null;
  /** Currently selected target (from Targeting3D). null = nothing selected. */
  selectedTargetId: string | null;
  /** Most recent cross-module task assignment. */
  currentTask: MissionTask | null;
}

export interface MissionActions {
  selectAsset: (id: string | null) => void;
  selectTarget: (id: string | null) => void;
  taskSelection: () => void;
  clearTask: () => void;
}
