// ─────────────────────────────────────────────────────────────────────────────
// TacticalCanvas — Shared Type Contracts
// ─────────────────────────────────────────────────────────────────────────────
// Every widget in this system shares these types. No component should define
// its own `any`-typed feature, asset, or alert shape.
// ─────────────────────────────────────────────────────────────────────────────

/** The four classifiable feature layers in the GEOINT module. */
export type FeatureType = 'infrastructure' | 'pathway' | 'organic' | 'zone';

/** A single geographic feature generated by the cluster engine. */
export interface GeoFeature {
  type: FeatureType;
  lng: number;
  lat: number;
}

/** Filter toggle state for each feature layer. */
export type FilterState = Record<FeatureType, boolean>;

/** The four top-level operational modules. */
export type ActiveModule = 'GEOINT' | 'RADAR' | 'TARGETING' | 'COMMAND';

// ─────────────────────────────────────────────────────────────────────────────
// Asset Model
// ─────────────────────────────────────────────────────────────────────────────

export type AssetStatus = 'ACTIVE' | 'RTB' | 'LOITER' | 'TRACKED';

export interface Asset {
  id: string;
  type: string;
  status: AssetStatus;
  fuel: number;
  /** Radar position — percentage-based, 0-100. */
  radarX: number;
  radarY: number;
  /** Heading in degrees for the radar marker. */
  heading: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// Alert Model
// ─────────────────────────────────────────────────────────────────────────────

export type AlertLevel = 'CRITICAL' | 'WARNING' | 'INFO';

export interface Alert {
  id: string;
  level: AlertLevel;
  msg: string;
  time: string;
  /** Optional link to the asset that caused the alert. */
  assetId?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Targeting Model
// ─────────────────────────────────────────────────────────────────────────────

export interface TargetMarker {
  id: string;
  type: string;
  x: number;
  y: number;
  size: 'sm' | 'md' | 'lg';
  dist: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Mission State — the shared selection context that flows across all modules
// ─────────────────────────────────────────────────────────────────────────────

export interface MissionState {
  /** Currently selected asset (from AssetList or Radar). null = nothing selected. */
  selectedAssetId: string | null;
  /** Currently selected target (from Targeting3D). null = nothing selected. */
  selectedTargetId: string | null;
}

export interface MissionActions {
  selectAsset: (id: string | null) => void;
  selectTarget: (id: string | null) => void;
}
